server:
  #  port: 0 #random port
  port: 1000 #random port

spring:
  application:
    name: user-service
  # mysql
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWD}

  #JPA
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  # Swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # hibernate logging
  logging:
    level:
      org.hibernate: info #${log.hibernate.level}

  # SERVER AUTO RELOAD
  devtools:
    livereload.enabled: true
  freemarker:
    cache: false

  # JWT Config
  jwt:
    secret: bXNoLWt5bS1jY2cta2p5LWxqaC1qa2gtcGF0cGF0LWdvb2QtbG9zdGFyay13aGF0aXNnb29kLXNzYWZ5LXNsZWVwLW5ld2plYW5zLWZpZ2h0aW5n
    access:
      expiration: 3600000
      header: Authorization

    refresh:
      expiration: 1209600000
      header: Authorization-refresh
  # OAuth
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 9d03d60cc88c7bea2a829ea7d86cd32d
            redirect-uri: http://localhost:5010/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
  servlet:
    multipart:
      max-request-size: 200MB
      max-file-size: 200MB
  #Redis
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

# Eureka
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Swagger path
springfox:
  documentation:
    swagger-ui:
      base-url: /users
    swagger:
      v2:
        path: /users

# file path
app:
  fileupload:
    uploadPath: ${UPLOAD_PATH}
    uploadDir: ${UPLOAD_DIR}
file.upload.uri: https://dokki.kr
